name: Mirror Repository

on:
  push:
    branches:
      - main  # ajuste conforme o nome do seu branch principal

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Push para o repositório de destino
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DESTINATION_REPO_TOKEN }}
          branch: main  # ajuste conforme o nome do seu branch principal
          repository: cristhians13/teste
