name: Sync Repositories

on:
  push:
    branches:
      - main  

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Sync changes to another repository
        uses: wei/mirror-sync@v1
        with:
          source_repo: ${{ github.repository }}  # Repositório de origem (projeto-pitII)
          source_branch: ${{ github.ref }}
          destination_repo: cristhians13/teste  # Repositório de destino
          destination_branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Token de acesso ao GitHub
