name: Sync Repository

on:
  push:
    branches:
      - main  # ou qualquer outra branch que deseja sincronizar

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Push changes to another repository
        run: |
          git remote add other_repo https://github.com/cristhians13/teste.git
          git push other_repo $GITHUB_REF
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 
