name: Push para teste

on:
  push:

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  push_teste:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Push para teste
        run: |
          git remote add teste https://github.com/cristhians13/teste.git
          git push teste HEAD
