name: Push and Sync

on:
  push:
    branches:
      - main

jobs:
  push_and_sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Push to main branch
      run: |
        git config --global user.email "cristhiansampaio@gmail.com"
        git config --global user.name "cristhians13"
      
    - name: Add vgx_origin remote
      run: git remote add vgx_origin https://github.com/cristhians13/actions.git
      
    - name: Push to vgx_origin main branch
      run: git push vgx_origin main
